#!/usr/bin/env python3
import nltk
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    #ensure proper usage
    if len(sys.argv) != 2:
        sys.exit('Usage: ./tweets @screen_name')

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    tweets = get_user_timeline(sys.argv[1].strip('@'), 50)

    if tweets == None:
        sys.exit("This screen name is protected or doesn't exist")

    analyzer = Analyzer(positives, negatives)

    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()

